[build]
  command = "npm run build"
  publish = "dist"

# Redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set proper MIME types for all JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
